<script setup>
defineProps({
  msg: {
    type: String,
    required: true,
  },
});
</script>

<template>
  <div class="greetings">
    <h1 class="green">{{ msg }}</h1>
  </div>
</template>

<!-- NOTE: EVERYTIME YOU SEE A STYLE ATRTRIBUTE INSIDE A .VUE FILE IS CONSIDERED AN AN ATTRIBUTE THAT YOU USE TO STYLE THE COMPONENT INTERNALLY. KEEP IN MIND , THIS STYLE TAG WTH THE 'SCOPED' ATTRIBUTE IS RESERVING ALL CSS PROPERTIES INSIDE THISTAG TO BE APPLY ONLY TO THIS FILE'S HTML ELEMENTS INSIDE THE <TEMPALTE> TAG 
  
RULE OF THUMB:
ONLY USE THIS STYLE TAG IF YOPU NEED TO STYLE SOMETHING SPECIFIC WITHIN THIS FILE, IF NOT, USE THE MAIN.CSS FILE

-->
<style scoped></style>